"""Add model table

Revision ID: 67cc006d5001
Revises: 66f72f04a1de
Create Date: 2025-01-18 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '67cc006d5001'
down_revision: Union[str, None] = '66f72f04a1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'model' not in table_names:
        op.create_table(
            'model',
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
            sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
            sa.Column('api_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
            sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
            sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
            sa.PrimaryKeyConstraint('id', name='pk_model')
        )
        with op.batch_alter_table('model', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_model_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_model_model_id'), ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'model' in table_names:
        op.drop_table('model')
    # ### end Alembic commands ### 