"""Add config table

Revision ID: add_config_table
Revises: 67cc006d5001
Create Date: 2025-07-02 05:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'add_config_table'
down_revision: Union[str, None] = '67cc006d5001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'config' not in table_names:
        op.create_table(
            'config',
            sa.Column('key', sa.VARCHAR(length=255), nullable=False),
            sa.Column('value', sa.VARCHAR(length=1000), nullable=False),
            sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True),
            sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
            sa.Column('updated_at', sa.TIMESTAMP(), nullable=False)
        )
        # 创建唯一索引
        op.create_index('ix_config_key', 'config', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    
    if 'config' in table_names:
        # 检查索引是否存在
        indexes = inspector.get_indexes('config')
        index_names = [index['name'] for index in indexes]
        if 'ix_config_key' in index_names:
            op.drop_index('ix_config_key', table_name='config')
        op.drop_table('config')
    # ### end Alembic commands ###