"""Add config table

Revision ID: add_config_table
Revises: 67cc006d5001
Create Date: 2025-07-02 05:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = 'add_config_table'
down_revision: Union[str, None] = '67cc006d5001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'config' not in table_names:
        op.create_table(
            'config',
            sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id', name='pk_config'),
            sa.UniqueConstraint('key', name='uq_config_key')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ### 